import type { Metadata, Viewport } from "next";
import { Inter, Space_Grotesk, IBM_Plex_Mono } from "next/font/google";
import { Providers } from "./providers";
import { PwaRegister } from "@/components/common/PwaRegister";
import { ThemeColorSync } from "@/components/common/ThemeColorSync";
import "./globals.css";

// Inter is what ChatGPT / Linear / Vercel / Stripe / most modern fintech
// dashboards use. Self-hosted via `next/font` so no extra request hits
// fonts.googleapis at runtime — the .woff2 ships from /_next/static and
// the font-display: swap behaviour comes free with the helper. The full
// 400/500/600/700 range covers every body / button / heading / numeric
// weight used across the app.
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  weight: ["400", "500", "600", "700"],
  display: "swap",
});

// Marketing-site display + numeric faces. Space Grotesk is the tight,
// geometric heading face from the StockEx design system (the brief's
// "Clash Display" alternative, but Google-hosted so it ships via next/font
// with zero runtime CDN hit). IBM Plex Mono carries prices, payouts, and
// stats with a tabular/mono feel. Both are scoped to the marketing pages
// via the `font-display` / `font-numeric` Tailwind families — the trading
// app keeps Inter everywhere.
const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
  variable: "--font-space-grotesk",
  weight: ["500", "600", "700"],
  display: "swap",
});

const plexMono = IBM_Plex_Mono({
  subsets: ["latin"],
  variable: "--font-plex-mono",
  weight: ["400", "500", "600"],
  display: "swap",
});

export const metadata: Metadata = {
  title: {
    default: "StockEx — Indian Trading Platform",
    template: "%s · StockEx",
  },
  description:
    "Trade Indian stocks, F&O, commodities, currencies, and crypto with StockEx — fast, transparent, dark-themed.",
  // Brand favicon. The source art (`/images/fevicon.png`) is 1024×1024 /
  // 2.3 MB — far too heavy to ship as a tab icon, so the entries below
  // point at the downscaled copies generated from it. Keep the 32px one
  // first: that's what the browser tab actually renders.
  icons: {
    icon: [
      { url: "/images/fevicon-32.png", type: "image/png", sizes: "32x32" },
      { url: "/images/fevicon-192.png", type: "image/png", sizes: "192x192" },
      { url: "/images/fevicon-512.png", type: "image/png", sizes: "512x512" },
    ],
    shortcut: "/images/fevicon-32.png",
    apple: "/images/fevicon-180.png",
  },
  // PWA — Apple-specific bits (Android/Chrome pick these up from
  // /manifest.webmanifest auto-generated by app/manifest.ts).
  applicationName: "StockEx",
  appleWebApp: {
    capable: true,
    title: "StockEx",
    // `default` (NOT `black-translucent`) so iOS reserves the status-bar
    // region in the installed PWA and the web canvas starts BELOW the
    // clock / Dynamic Island. `black-translucent` overlaid the status bar
    // over the top of every full-screen surface (terminal chart header,
    // option-chain dialog, add-funds wizard, admin headers…) — the
    // "Add to Home Screen content overlaps the clock" bug. With `default`
    // the status bar shows a solid themeColor band and nothing overlaps.
    statusBarStyle: "default",
  },
  // Manifest path is auto-injected by Next when app/manifest.ts
  // exists; declaring it here is belt-and-braces for older crawlers.
  manifest: "/manifest.webmanifest",
  // Disable every browser's "Translate page?" infobar. Refreshing the
  // app kept surfacing the prompt on Hindi/regional-locale devices, and
  // the trading numbers MUST NOT be auto-translated (entry → "prawesh",
  // BUY/SELL → "kharidein/bechein") because the broker UI relies on
  // exact English labels for SOPs/screen-shares. We cover Google /
  // Googlebot / Yandex translators plus an explicit Content-Language
  // header so browsers don't guess based on visible content.
  other: {
    google: "notranslate",
    googlebot: "notranslate",
    yandex: "notranslate",
    "content-language": "en",
    "google-site-verification": "",
    // Modern counterpart to appleWebApp.capable's
    // `apple-mobile-web-app-capable` — Chrome deprecated the apple-prefixed
    // tag and logs a console warning unless this standard one is present.
    "mobile-web-app-capable": "yes",
  },
};

export const viewport: Viewport = {
  // Match the OS chrome (Android status bar / Chrome address bar) to
  // the app's current theme instead of the brand emerald everywhere.
  // The two media-keyed entries let the BROWSER pick the right one
  // when there's no user-set theme; the <ThemeColorSync> client
  // component below overrides this in real time when the user flips
  // light/dark from Profile → Preferences so the top safe-area band
  // never stays green on a light-theme app screen.
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#ffffff" },
    { media: "(prefers-color-scheme: dark)", color: "#0a0a0a" },
  ],
  width: "device-width",
  initialScale: 1,
  // Lock pinch-zoom / double-tap-zoom on mobile so the installed PWA
  // (and the mobile browser view) feels like a native shell — user
  // spec: "zoom in zoom out mat ho". Desktop browsers ignore these,
  // accessibility users can still use Ctrl/Cmd-+/- which `userScalable`
  // doesn't block.
  maximumScale: 1,
  minimumScale: 1,
  userScalable: false,
  // Deliberately NOT `cover`. With `viewport-fit=cover` iOS draws the web
  // canvas UNDER the status bar / Dynamic Island, so every top-anchored
  // surface (terminal chart header, option-chain dialog, add-funds wizard)
  // overlapped the clock in the installed PWA. Default fit keeps content
  // inside the safe area — iOS reserves a solid themeColor status-bar band
  // on top and nothing overlaps, on any page or popup.
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  // `translate="no"` on <html> is the canonical W3C signal to all
  // translation engines (Chrome, Edge, Safari, third-party widgets)
  // that the page must not be auto-translated. Combined with the
  // <meta name="google" content="notranslate" /> in metadata.other,
  // it prevents the "Translate page?" popup from showing on refresh
  // — important because mistranslated trading labels (BUY → kharidein)
  // would be unsafe.
  return (
    <html
      lang="en"
      translate="no"
      suppressHydrationWarning
      className={`notranslate ${inter.variable} ${spaceGrotesk.variable} ${plexMono.variable}`}
    >
      <body className="notranslate font-sans antialiased" translate="no">
        <PwaRegister />
        <ThemeColorSync />
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
