"""Admin panel routers (mounted under /api/v1/admin)."""

from fastapi import APIRouter

from app.api.v1.admin import (
    accounts,
    admin_book,
    auth,
    branding,
    brokerage,
    brokers,
    dashboard,
    expiry_overrides,
    fund,
    games_settings,
    infoway,
    instruments,
    kuber,
    kyc,
    ledger,
    management,
    marketwatch,
    me,
    money_transactions,
    netting,
    notifications,
    patti,
    payin_out,
    pnl_sharing,
    push,
    referral,
    reports,
    risk,
    sa_ledger,
    settings,
    market_control,
    support,
    trading,
    transaction_history,
    users,
    zerodha,
    zerodha_auto_login,
)

router = APIRouter(prefix="/admin", tags=["admin"])
router.include_router(accounts.router)
router.include_router(admin_book.router)
router.include_router(sa_ledger.router)
router.include_router(auth.router)
router.include_router(dashboard.router)
router.include_router(users.router)
router.include_router(risk.router)
router.include_router(netting.router)
router.include_router(trading.router)
router.include_router(payin_out.router)
router.include_router(brokerage.router)
router.include_router(instruments.router)
router.include_router(marketwatch.router)
router.include_router(ledger.router)
router.include_router(money_transactions.router)
router.include_router(transaction_history.router)
router.include_router(market_control.router)
router.include_router(reports.router)
router.include_router(settings.router)
router.include_router(expiry_overrides.router)
router.include_router(zerodha.router)
router.include_router(zerodha_auto_login.router)
router.include_router(infoway.router)
router.include_router(kyc.router)
router.include_router(management.router)
router.include_router(brokers.router)
router.include_router(pnl_sharing.router)
router.include_router(notifications.router)
router.include_router(support.router)
router.include_router(branding.router)
router.include_router(push.router)
router.include_router(games_settings.router)
router.include_router(referral.router)
router.include_router(me.router)
router.include_router(kuber.router)
router.include_router(fund.router)
router.include_router(patti.router)
